directories:
  logging: ../conf/log
  rules: rules
  lib: lib
  param: parameters
  config: config  # Folder from which configuration files will be loaded
location:
  latitude: 52.52437
  longitude: 13.41053
  elevation: 43
mqtt:
  connection:
    client_id: HABApp
    host: localhost
    password: ''
    port: 1883
    tls: false
    tls_insecure: false
    user: ''
  publish:
    qos: 0
    retain: false
  subscribe:
    qos: 0
    topics:
    - '#'
    - 0
  general:
    listen_only: false
openhab:
  connection:
    host: localhost
    password: ''
    port: 8080
    user: ''
  general:
    listen_only: false
    wait_for_openhab: true
  ping:
    enabled: true
    interval: 10
    item: Ping
